### PR TITLE
tvos support

### PR DESCRIPTION
**Pull request by paulocoutinhox**

### CODE REVIEW

**Comment by halx99** [comment]
Well, you needs add process in script: https://github.com/axys1/buildware/blob/main/1k/build1.sh#L95, not only yml

**Comment by paulocoutinhox** [comment]
@halx99 added all scripts...what more need be changed?

**Comment by halx99** [comment]
Let me merge firstly for github action checks

**Comment by halx99** [comment]
The ci build finished, you can download tv prebuilt from: https://github.com/axys1/buildware/actions/runs/2983205738 and test them

**Comment by paulocoutinhox** [comment]
It build some libs for iOS instead of tvOS.

Can you add me on whatsapp or hangout for fast talk?
Email, chat, google, hangout: paulocoutinhox@gmail.com
WhatsApp: +5521993860010

**Comment by halx99** [comment]
OK

**Pull request merged**
